version: '3'

services:
  golang:
    build: .
    tty: true
    ports: 
      - "8080:8080"
    container_name: charaboti
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: golang
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    container_name: mysql-container