version: '3'

services:
  golang:
    build: .
    tty: true
    ports: 
      - "80:80"
    container_name: charaboti
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: golang
    container_name: mysql-container