version: '3'

services:
  golang:
    build: .
    tty: true
    ports: 
      - "8080:8080"
    container_name: charaboti
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: golang
    # volumes:
    #   - .:/var/lib/mysql
    container_name: mysql-container