version: '3'

services:
  app:
    build: .
    tty: true
    ports: 
      - "8080:8080"
    container_name: charaboti
    depends_on:
      - mysql
mysql:
  image: mysql:5.7.22
  environment:
    MYSQL_ROOT_PASSWORD: golang
  container_name: mysql-container