version: '3'

services:
  golang:
    build: .
    tty: true
    ports: 
      - "8080:8080"
    container_name: charaboti
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: golang
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    container_name: mysql-container