version: '3'

services:
  app:
    build: .
    tty: true
    ports: 
      - "8080:8080"
    container_name: charaboti
    depends_on:
      - mysql
mysql:
  image: latest
  environment:
    MYSQL_ROOT_PASSWORD: golang
    MYSQL_USER: golang
    MYSQL_PASSWORD: golang
    MYSQL_DATABASE: golang
  container_name: mysql-container